apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-event-test
  description: An example of a Backstage application - UPDATE OVER PR.
  annotations:
    github.com/project-slug: backtostage/github-event-test
spec:
  type: service
  owner: angeliski
  lifecycle: experimental
